#!/usr/bin/env python
# encoding: utf-8
import os
import sys
from optparse import OptionParser

import metainfo
import utils


USAGE = "%prog <delta> <file1> [<file2>...]"


def adjust_time(name, delta):
    dct = metainfo.read(name)
    date = dct["creation_time"] + delta

    keywords = {"creation_time": date.strftime(metainfo.DATETIME_FORMAT)}

    tmpname = "tmp-" + name
    metainfo.write(name, tmpname, keywords)

    os.rename(name, name + ".orig")
    os.rename(tmpname, name)


def main():
    parser = OptionParser(usage=USAGE)
    (options, args) = parser.parse_args()

    if len(args) < 2:
        parser.error("Missing args")

    delta = utils.parse_delta(args[0])

    for name in args[1:]:
        print "Processing %s" % name
        adjust_time(name, delta)

    return 0


if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
